name: wbs_desktop
version: 1.0.0+1
publish_to: kuhlen
description: A simple desktop app to read serial communication data from RS232.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  window_manager: ^0.3.7
  screen_retriever: ^0.1.9
  flutter_libserialport: ^0.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

